// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTest.Models;

namespace WebTest.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190910142401_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebTest.Models.JBlog", b =>
                {
                    b.Property<int>("JBlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Subject");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("JBlogId");

                    b.ToTable("JBlogs");
                });

            modelBuilder.Entity("WebTest.Models.JImage", b =>
                {
                    b.Property<int>("JImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Subject");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("JImageId");

                    b.ToTable("JImages");
                });

            modelBuilder.Entity("WebTest.Models.JPost", b =>
                {
                    b.Property<int>("JPostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<int?>("JBlogId");

                    b.Property<string>("Title");

                    b.HasKey("JPostId");

                    b.HasIndex("JBlogId");

                    b.ToTable("JPosts");
                });

            modelBuilder.Entity("WebTest.Models.JPost", b =>
                {
                    b.HasOne("WebTest.Models.JBlog", "JBlog")
                        .WithMany("JPosts")
                        .HasForeignKey("JBlogId");
                });
#pragma warning restore 612, 618
        }
    }
}
