/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuwd_jlive_JFFmpeg */

#ifndef _Included_com_xuwd_jlive_JFFmpeg
#define _Included_com_xuwd_jlive_JFFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuwd_jlive_JFFmpeg
 * Method:    getFFmpegInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xuwd_jlive_JFFmpeg_getFFmpegInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_xuwd_jlive_JFFmpeg
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xuwd_jlive_JFFmpeg_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xuwd_jlive_JFFmpeg
 * Method:    pushCameraData
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_xuwd_jlive_JFFmpeg_pushCameraData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_xuwd_jlive_JFFmpeg
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xuwd_jlive_JFFmpeg_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
