/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuwd_jlive_JFFmpeg_SingletonInstance */

#ifndef _Included_com_xuwd_jlive_JFFmpeg_SingletonInstance
#define _Included_com_xuwd_jlive_JFFmpeg_SingletonInstance
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
