/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuwd_jimagetest_NativeLibrary */

#ifndef _Included_com_xuwd_jimagetest_NativeLibrary
#define _Included_com_xuwd_jimagetest_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuwd_jimagetest_NativeLibrary
 * Method:    yuv420pToRGBA
 * Signature: ([BII[B)V
 */
JNIEXPORT void JNICALL Java_com_xuwd_jimagetest_NativeLibrary_yuv420pToRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
